name: rmrl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - networkx
  - pytorch::pytorch
  - tensorboard
  - pyg::pyg
  - matplotlib
  - jupyterlab
  - tqdm
  - ipywidgets
  - pip
  - pip:
#      - mujoco-py<2.2,>=2.1
#      - gym[mujoco]
#      - stable-baselines3==1.6.0
      - -e ./stable-baselines3
      - git+https://github.com/sarah-keren/multi_taxi
